spring:
  application:
    name: config-service
  profiles:
    active: ${APP_PROFILE}
  security:
    user:
      name: ${CONFIG_SERVICE_SECURITY_USERNAME}
      password: ${CONFIG_SERVICE_SECURITY_PASSWORD}
      roles: ${CONFIG_SERVICE_SECURITY_ROLE}
  cloud:
    config:
      server:
        git:
          default-label: ${CONFIG_SERVICE_GIT_URI_BRANCH}
          uri: ${CONFIG_SERVICE_GIT_URI}
          search-paths: ${CONFIG_SERVICE_GIT_DIR_PATH}
          username: ${CONFIG_SERVICE_GIT_URI_USERNAME}
          password: ${CONFIG_SERVICE_GIT_URI_PASSWORD}

server:
  port: ${CONFIG_SERVICE_PORT}
  servlet:
    context-path: /${CONFIG_SERVICE_CONTEXT_PATH}